### ISSUE TITLE
Feature Request: Implement rd_kafka_message_timestamp

### ISSUE THREAD

**Issue by muenalan** [trinitum/perl-Kafka-Librd#10]
Hi Pavel, 

Looked into it, landed here https://github.com/edenhill/librdkafka/issues/1016 and it seems it came somewhere 0.10 into Kafka. What is you take on adding this into this module ?

PS: thumbs up for this module by the way. It just works, thats it.

**Comment by trinitum** [comment]
Hi @muenalan, I don't do much Perl or Kafka recently, and my free time is somewhat limited, so I unfortunately can't spend any on this.

**Comment by plicease** [comment]
See #14

**Comment by plicease** [comment]
#14 is released as 0.12
