### ISSUE TITLE
Build on CentOS7

### ISSUE THREAD

**Issue by mrdvt92** [trinitum/perl-Kafka-Librd#20]
I had the hardest time building this package on CentOS 7 and so I added my spec to my fork and the required updates to drop Alien that is not needed under package managed systems.

https://github.com/mrdvt92/Kafka-Librd

$ git clone https://github.com/mrdvt92/Kafka-Librd.git
$ cd Kafka-Librd/
$ perl Makefile.PL
$ make
$ make test
$ make dist
$ rpmbuild -ta Kafka-Librd-0.14.tar.gz

I'm not exactly sure how to package the deltas as a patch so that you could just merge this fork into your master. In any event, this is done for any others out there.

**Comment by plicease** [comment]
Installs fine for me on CentOS 7.  Please next time report what doesn't work instead of spending a lot of time on a fork that will never be merged.

**Comment by mrdvt92** [comment]
> Installs fine for me on CentOS 7. 

Alien-Base is not available as RPMs and it's unsupported dependencies are deep.  So, not an option for us.

My team requires RPM deployments and Alien is not needed for package managed systems like CentOS 7.  So, my fork is simply to drop all of the Alien build hooks and add back the one LIB line in Makefile.PL and it builds.
