### ISSUE TITLE
Build warning: label ‘CROAK’ defined but not used

### ISSUE THREAD

**Issue by mrdvt92** [trinitum/perl-Kafka-Librd#22]
This is just a warning and I don't know C well enough to determine why. The tests pass an there does not appear to be any operational impact.

My Kafka versions on CentOS Linux release 7.7.1908 (Core)
librdkafka-devel-0.11.5-1.el7.x86_64
librdkafka-0.11.5-1.el7.x86_64

`
gcc -c   -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic   -DVERSION=\"0.14\" -DXS_VERSION=\"0.14\" -fPIC "-I/usr/lib64/perl5/CORE"   rdkafkaxs.c

rdkafkaxs.c: In function ‘krd_expand_topic_partition_list’:

rdkafkaxs.c:82:1: warning: label ‘CROAK’ defined but not used [-Wunused-label]

 CROAK:

 ^

`

**Comment by plicease** [comment]
Thank you for reporting this.  Fixed in 37adb16294a1370ec028155748db2087723d2586.
