### ISSUE TITLE
Move commit_message to Message object

### ISSUE THREAD

**Issue by mrdvt92** [trinitum/perl-Kafka-Librd#23]
Is it possible to copy the commit_message method to the Kafka::Librd::Message object

$err = $kafka->commit_message($msg, $async);

should be

$err = $msg->commit;
$err = $msg->commit($async);

**Comment by plicease** [comment]
probably not?  But PR to prove me wrong would be considered.

The commit_message function takes an `rd_kafka_t` pointer, which I don't think you can get from the `rd_kafka_message_t` pointer.

```c
RD_EXPORT rd_kafka_resp_err_t
rd_kafka_commit_message (rd_kafka_t *rk, const rd_kafka_message_t *rkmessage,
                         int async);
```
