### ISSUE TITLE
Error handling of produce method

### ISSUE THREAD

**Issue by harmathy** [trinitum/perl-Kafka-Librd#33]
As of now the produce method only returns -1 in case of an error. But there is no way to handle different errors appropriately or get an error description.

**Comment by harmathy** [comment]
The [documentation](https://github.com/edenhill/librdkafka/blob/30004c6c6caa81861c0abf800c7026b799e114e5/src/rdkafka.h#L4227) of `rd_kafka_produce` suggests to use `errno` and `rd_kafka_errno2err` to handle errors. But the [documentation](https://github.com/edenhill/librdkafka/blob/30004c6c6caa81861c0abf800c7026b799e114e5/src/rdkafka.h#L705) of `rd_kafka_errno2err` states, that using `rd_kafka_last_error` would be a better choice.

Therefore most probably `rd_kafka_last_error` should be implemented for error handling.

**Comment by plicease** [comment]
Yup this seems like a good idea.  Patches welcome.
